# -*- coding: utf-8 -*-
"""neptune-integration

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YftN6Uk51kw2ipyKGrwbj1q_hDyJ8EhE
"""

import neptune

from getpass import getpass


print("The program will shortly ask for your API token")
api_token = getpass("Enter your private neptune AI token:") # get it from your neptune UI

workspace = "somyagoel"
project_name = "Neptune-Integration"
project = f"{workspace}/{project_name}"
print(project)

run = neptune.init_run(
    project=project,
    api_token=api_token,
    capture_hardware_metrics=True,
    capture_stderr=True,
    capture_stdout=True,
)  