wandb_version: 1

architecture:
  desc: null
  value: Alex-Net
dataset:
  desc: null
  value: CIFAR-10
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684798249.931277
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.11.2
      5: 0.15.3
      8:
      - 5
